"""
1. User guesses the number generated by the computer.
2. Computer guesses the number generated by the user.
"""

from random import randint

# def user_guess(x):
# 	random_no = randint(1, x)
# 	guess_no = 0
# 	steps = 1

# 	while guess_no != random_no :

# 		guess_no = int(input(f"Guess a number between 1 and {x}: "))

# 		if guess_no < random_no:
# 			print("Too low ")
# 		else:
# 			print("Too high ")

# 		steps += 1

# 	print(f"Great job! You guessed correcty {random_no}. It took you {steps} guesses.")


# user_guess(20)

def computer_guess():
	low = int(input("Give me the low of the interval: "))
	high = int(input("Give me the high of the interval: "))
	feedback = ""
	steps = 0

	while feedback != "C":

		random_no = randint(low, high)

		feedback = input({f"{random_no}! Is it correct(C), too low(L), too high(H)?"}).upper()

		if feedback == "L":
			low = random_no - 1
			
		elif feedback == "H":
			high = random_no + 1
		
		steps += 1

	print(f"Great job! You guessed correcty {random_no}. It took you {steps} guesses.")


computer_guess()


